name: PAT
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the build number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # iOS style icons
  cupertino_icons: ^1.0.6

  # Required dependencies for your project
  flutter_map: ^4.0.0
  latlong2: ^0.8.1  # For defining coordinates on the map
  url_launcher: ^6.1.6  # For launching URLs
  video_player: ^2.5.1
  carousel_slider: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting package for recommended code practices
  flutter_lints: ^3.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true

  # Asset declarations
  assets:
    - assets/logo.jpg
    - assets/video/ee.mp4
    - assets/donate.jpg
    - assets/exemple1.jpg
    - assets/exemple2.jpg
    - assets/exemple3.jpg
    - assets/exemple4.jpg

  # Uncomment this to add more image assets
  #   - images/a_dot_ham.jpeg

  # Font example if you want to add custom fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
